name: observable-speaker-infra
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - shared-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperSecret123!"
      ACCEPT_EULA: "Y"
    networks:
      - shared-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "55680:55680"
      - "8888:8888" 
      - "8889:8889"
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
    volumes:
      - ./otel-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - shared-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - shared-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./otel-config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shared-network

networks:
  shared-network:
    name: observablespeakers_network